name: Downgrade
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != format('refs/heads/{0}', github.event.repository.default_branch) }}
jobs:
  downgrade:
    name: Downgrade
    strategy:
      fail-fast: false
      matrix:
        group:
          - Layers
          - BasicNeuralDE
          - AdvancedNeuralDE
          - Newton
          - QA
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      group: "${{ matrix.group }}"
      julia-version: "1.10"
    secrets: "inherit"
